# Generated by Django 6.0.2 on 2026-02-28 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("categoria_id", models.AutoField(primary_key=True, serialize=False)),
                ("categoria_nombre", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
                "db_table": "categorias",
            },
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                ("editorial_id", models.AutoField(primary_key=True, serialize=False)),
                ("editorial_nombre", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "Editorial",
                "verbose_name_plural": "Editoriales",
                "db_table": "editoriales",
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("usuario_id", models.AutoField(primary_key=True, serialize=False)),
                ("usuario_nombre", models.CharField(max_length=100)),
                ("usuario_aPaterno", models.CharField(max_length=100)),
                (
                    "usuario_aMaterno",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "usuario_nombre_acceso",
                    models.CharField(max_length=100, unique=True),
                ),
                ("usuario_password", models.CharField(max_length=255)),
                (
                    "usuario_clave_acceso",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "matricula_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "usuario_rol",
                    models.CharField(
                        choices=[
                            ("Administrador", "Administrador"),
                            ("Docente", "Docente"),
                            ("Alumno", "Alumno"),
                        ],
                        default="Alumno",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
            },
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("libro_id", models.AutoField(primary_key=True, serialize=False)),
                ("libro_titulo", models.CharField(max_length=300)),
                ("libro_autor", models.CharField(max_length=300)),
                ("libro_isbn", models.CharField(max_length=20, unique=True)),
                ("libro_ejemplares", models.IntegerField(default=1)),
                ("libro_descripcion", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="categoria_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="libros",
                        to="biblioteca.categoria",
                    ),
                ),
                (
                    "editorial",
                    models.ForeignKey(
                        db_column="editorial_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="libros",
                        to="biblioteca.editorial",
                    ),
                ),
            ],
            options={
                "verbose_name": "Libro",
                "verbose_name_plural": "Libros",
                "db_table": "libros",
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                ("prestamo_id", models.AutoField(primary_key=True, serialize=False)),
                ("prestamo_fecha_salida", models.DateField()),
                ("prestamo_fecha_entrega_esperada", models.DateField()),
                (
                    "prestamo_fecha_devolucion_real",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "prestamo_estatus",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Devuelto", "Devuelto"),
                            ("Vencido", "Vencido"),
                        ],
                        default="Activo",
                        max_length=10,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        db_column="libro_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestamos",
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestamos",
                        to="biblioteca.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "db_table": "prestamos",
            },
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                ("multa_id", models.AutoField(primary_key=True, serialize=False)),
                ("multa_monto", models.DecimalField(decimal_places=2, max_digits=8)),
                ("multa_motivo", models.CharField(max_length=300)),
                (
                    "multa_estatus",
                    models.CharField(
                        choices=[("Pagada", "Pagada"), ("Pendiente", "Pendiente")],
                        default="Pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        db_column="prestamo_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="multas",
                        to="biblioteca.prestamo",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="multas",
                        to="biblioteca.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multa",
                "verbose_name_plural": "Multas",
                "db_table": "multas",
            },
        ),
        migrations.CreateModel(
            name="Apartado",
            fields=[
                ("apartado_id", models.AutoField(primary_key=True, serialize=False)),
                ("apartado_fecha", models.DateField()),
                ("apartado_fecha_expiracion", models.DateField()),
                (
                    "apartado_estatus",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Cancelado", "Cancelado"),
                            ("Convertido", "Convertido"),
                        ],
                        default="Activo",
                        max_length=12,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        db_column="libro_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apartados",
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="apartados",
                        to="biblioteca.usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Apartado",
                "verbose_name_plural": "Apartados",
                "db_table": "apartados",
            },
        ),
    ]
