# Generated by Django 6.0.2 on 2026-02-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="libro", name="categoria",),
        migrations.RemoveField(model_name="libro", name="editorial",),
        migrations.RemoveField(model_name="prestamo", name="libro",),
        migrations.RemoveField(model_name="multa", name="prestamo",),
        migrations.RemoveField(model_name="multa", name="usuario",),
        migrations.RemoveField(model_name="prestamo", name="usuario",),
        migrations.AlterModelOptions(name="usuario", options={},),
        migrations.AlterField(
            model_name="usuario",
            name="matricula_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="usuario_aMaterno",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="usuario_clave_acceso",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.DeleteModel(name="Apartado",),
        migrations.DeleteModel(name="Categoria",),
        migrations.DeleteModel(name="Editorial",),
        migrations.DeleteModel(name="Libro",),
        migrations.DeleteModel(name="Multa",),
        migrations.DeleteModel(name="Prestamo",),
    ]
