# Generated by Django 6.0.2 on 2026-02-28 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0002_remove_libro_categoria_remove_libro_editorial_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                ("categoria_id", models.AutoField(primary_key=True, serialize=False)),
                ("categoria_nombre", models.CharField(max_length=100)),
            ],
            options={"db_table": "categorias",},
        ),
        migrations.CreateModel(
            name="Editorial",
            fields=[
                ("editorial_id", models.AutoField(primary_key=True, serialize=False)),
                ("editorial_nombre", models.CharField(max_length=200)),
            ],
            options={"db_table": "editoriales",},
        ),
        migrations.CreateModel(
            name="Libro",
            fields=[
                ("libro_id", models.AutoField(primary_key=True, serialize=False)),
                ("libro_titulo", models.CharField(max_length=300)),
                ("libro_autor", models.CharField(max_length=200)),
                ("libro_isbn", models.CharField(max_length=20, unique=True)),
                ("libro_ejemplares", models.IntegerField(default=1)),
                ("libro_descripcion", models.TextField(blank=True, default="")),
                (
                    "categoria",
                    models.ForeignKey(
                        db_column="categoria_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.categoria",
                    ),
                ),
                (
                    "editorial",
                    models.ForeignKey(
                        db_column="editorial_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.editorial",
                    ),
                ),
            ],
            options={"db_table": "libros",},
        ),
        migrations.CreateModel(
            name="Apartado",
            fields=[
                ("apartado_id", models.AutoField(primary_key=True, serialize=False)),
                ("apartado_fecha", models.DateField()),
                ("apartado_fecha_expiracion", models.DateField()),
                (
                    "apartado_estatus",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Cancelado", "Cancelado"),
                            ("Convertido", "Convertido"),
                        ],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.usuario",
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        db_column="libro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
            ],
            options={"db_table": "apartados",},
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                ("prestamo_id", models.AutoField(primary_key=True, serialize=False)),
                ("prestamo_fecha_salida", models.DateField()),
                ("prestamo_fecha_entrega_esperada", models.DateField()),
                (
                    "prestamo_fecha_devolucion_real",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "prestamo_estatus",
                    models.CharField(
                        choices=[
                            ("Activo", "Activo"),
                            ("Devuelto", "Devuelto"),
                            ("Vencido", "Vencido"),
                        ],
                        default="Activo",
                        max_length=20,
                    ),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        db_column="libro_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.libro",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.usuario",
                    ),
                ),
            ],
            options={"db_table": "prestamos",},
        ),
        migrations.CreateModel(
            name="Multa",
            fields=[
                ("multa_id", models.AutoField(primary_key=True, serialize=False)),
                ("multa_monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("multa_motivo", models.CharField(max_length=255)),
                (
                    "multa_estatus",
                    models.CharField(
                        choices=[("Pagada", "Pagada"), ("Pendiente", "Pendiente")],
                        default="Pendiente",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        db_column="usuario_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.usuario",
                    ),
                ),
                (
                    "prestamo",
                    models.ForeignKey(
                        db_column="prestamo_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="biblioteca.prestamo",
                    ),
                ),
            ],
            options={"db_table": "multas",},
        ),
    ]
