# Generated by Django 5.2 on 2026-03-12 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0004_remove_usuario_usuario_clave_acceso_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="multa", name="multa_monto",),
        migrations.AddField(
            model_name="multa",
            name="multa_dias_bloqueo",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="multa",
            name="multa_fecha_fin",
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="multa",
            name="multa_fecha_inicio",
            field=models.DateField(default=datetime.date(2024, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usuario",
            name="usuario_bloqueado_hasta",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="multa",
            name="multa_estatus",
            field=models.CharField(
                choices=[("Activa", "Activa"), ("Cumplida", "Cumplida")],
                default="Activa",
                max_length=20,
            ),
        ),
    ]
