# Generated by Django 5.2 on 2026-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "biblioteca",
            "0005_remove_multa_multa_monto_multa_multa_dias_bloqueo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="usuario_rol",
            field=models.CharField(
                choices=[("usuario", "Usuario"), ("admin", "Admin")],
                default="usuario",
                max_length=20,
            ),
        ),
    ]
