# Generated by Django 5.2.4 on 2026-03-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0006_usuario_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="apartado",
            name="apartado_fecha_asignacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="apartado",
            name="apartado_fecha_limite_recogida",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prestamo",
            name="prestamo_dias_plazo",
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name="apartado",
            name="apartado_estatus",
            field=models.CharField(
                choices=[
                    ("Pendiente", "Pendiente"),
                    ("Asignado", "Asignado"),
                    ("Cancelado", "Cancelado"),
                    ("Convertido", "Convertido"),
                ],
                default="Pendiente",
                max_length=20,
            ),
        ),
    ]
