# Generated by Django 5.2.4 on 2026-03-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0007_apartado_apartado_fecha_asignacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="prestamo_dias_plazo",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
