# Generated by Django 5.2 on 2026-03-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_alter_prestamo_prestamo_dias_plazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='usuario_correo',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
