# Generated by Django 5.2 on 2026-03-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_usuario_usuario_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartado',
            name='apartado_estatus',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignado', 'Asignado'), ('Cancelado', 'Cancelado'), ('Convertido', 'Convertido'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='prestamo_estatus',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Activo', 'Activo'), ('Devuelto', 'Devuelto'), ('Vencido', 'Vencido'), ('Rechazado', 'Rechazado')], default='Activo', max_length=20),
        ),
    ]
